feat: add submit auth use jsonp in did auth
ArcBlock/forge-js pull request #485
Opened 2020-12-08 08:42 UTC by leermao

添加 jsonp 连接 方便验证 did auth

2020-12-08 08:55 UTC, wangshijun requested changes

2020-12-08 08:55 UTC, wangshijun commented on did/did-auth/lib/handlers/wallet.js
> +    app.get(`${pathname}/submit`, ensureWallet, ensureContext, ensureSignedJson, onAuthResponse);
新 API 考虑加个测试

2020-12-08 08:55 UTC, wangshijun commented on CHANGELOG.md
> +- [skip travis] update readme
changelog

2020-12-11 02:29 UTC, leermao commented
![image](https://user-images.githubusercontent.com/11629887/101854062-b7874f80-3b9b-11eb-90d6-60b55b4bbc75.png)

2020-12-11 06:18 UTC, wangshijun approved these changes

2020-12-11 06:18 UTC, merged